In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [3]:
colz = list(df.columns)
colz = [col.lower().replace(' ', '_') for col in colz]

df.columns = colz
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [4]:
df.dtypes

engine_displacement      int64
num_cylinders          float64
horsepower             float64
vehicle_weight         float64
acceleration           float64
model_year               int64
origin                  object
fuel_type               object
drivetrain              object
num_doors              float64
fuel_efficiency_mpg    float64
dtype: object

In [5]:
string_colz = list(df.dtypes[df.dtypes== 'object'].index)
for col in string_colz:
    df[col] = df[col].str.lower().str.replace(' ','_').str.replace('-','_')

df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,europe,gasoline,all_wheel_drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,usa,gasoline,front_wheel_drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,europe,gasoline,front_wheel_drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,usa,diesel,all_wheel_drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,europe,gasoline,all_wheel_drive,2.0,12.488369

In [6]:
for col in  df.columns:
    print('\n %%%%%%%%%%%%%%%%%%%%%%%%%%%')
    print(col)
    if (df[col].dtypes == 'object') | (col in ['num_doors','model_year']):
        print(df[col].value_counts())
    else:
        df[col].describe()

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
engine_displacement

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
num_cylinders

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
horsepower

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
vehicle_weight

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
acceleration

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
model_year
model_year
2003    447
2002    446
2018    443
2004    440
2021    438
2015    435
2006    431
2010    428
2014    427
2005    427
2012    426
2016    424
2013    420
2019    420
2022    419
2008    415
2007    410
2011    404
2009    403
2020    400
2017    391
2001    388
2023    214
2000    208
Name: count, dtype: int64

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
origin
origin
europe    3254
asia      3247
usa       3203
Name: count, dtype: int64

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
fuel_type
fuel_type
gasoline    4898
diesel      4806
Name: count, dtype: int64

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
drivetrain
drivetrain
all_wheel_drive      4876
front_wheel_drive    4828
Name: count, dtype: int64

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
num_doors
num_doors
 0.0    3551
 1.0    2192
-1.0    2183
-2.0     594
 2.0     563
 3.0      58
-3.0      56
-4.0       4
 4.0       1
Name: count, dtype: int64

 %%%%%%%%%%%%%%%%%%%%%%%%%%%
fuel_efficiency_mpg

In [ ]:
imprt seaborn as sns